### PR TITLE
Feature/optimized async and hopac combinator usage

### PR DESCRIPTION
**Pull request by polytypic**
These optimizations avoid some unnecessary allocations.

### CODE REVIEW

**Comment by polytypic** [comment]
No hurry, but pinging @kolektiv just in case as you don't seem to be watching this repository. :)

**Comment by kolektiv** [comment]
Oh! Well pinged, I hadn't seen this. Somehow I'm not watching my own repo... I'll fix that!

Thanks! I'd pretty much mechanically translated the async logic - this is much more sensible :)

**Comment by kolektiv** [comment]
I'll just bump the version too and it'll go straight out...

**Comment by kolektiv** [comment]
And that's live! Once NuGet gets the indexes updated, rc05 of the core libraries will be available. Thanks again @polytypic!

**Pull request merged**
