### PR TITLE
Feature/optimized async and hopac integration

### PR DESCRIPTION
**Pull request by polytypic**
Here are a few further optimizations I didn't notice in the morning.

### CODE REVIEW

**Comment by polytypic** [comment]
Another gentle ping @kolektiv :)

**Comment by polytypic** [comment]
BTW, depending on how the integration functions are being used, it may be better (or necessary) to use [`Hopac.queueAsTask`](http://hopac.github.io/Hopac/Hopac.html#dec:val%20Hopac.Hopac.queueAsTask).  The difference between `Hopac.queueAsTask` and `Hopac.startAsTask` is that the former queues the job to be executed (later) while the latter immediately starts executing the job (on the current thread).

**Comment by neoeinstein** [comment]
Is that all of the `Async`? No more? ;-)

**Comment by kolektiv** [comment]
Fantastic :) Thanks, these changes clean things up nicely and should avoid a fair few extra cycles!

**Comment by kolektiv** [comment]
Just bumped this so it'll be public as rc06 fairly shortly. In terms of all of the `Async` - yes, I believe there is now no async in the Hopac builds. 😄

**Comment by kolektiv** [comment]
It's a good point on the `startAsTask`/`queueAsTask` distinction as well -- I'm going to have a think about that. I don't think it should make too much difference given how most servers use it, but I might benchmark that assumption soon!

**Pull request merged**
